checkpoint_file: outputs/8-16/aero-nfft=512-hl=256/checkpoint.th

device: cpu

experiment:
  # @package experiment
  name: aero-nfft=512-hl=256

  # Dataset related
  lr_sr: 8000 # low resolution sample rate
  hr_sr: 16000 # high resolution sample rate
  segment: 2
  stride: 2
  pad: true
  upsample: false
  batch_size: 16

  nfft: 512
  hop_length: 256

  # models related
  model: aero
  aero:
    in_channels: 1
    out_channels: 1
    channels: 48
    growth: 2

    # STFT
    nfft: 512
    hop_length: 256
    end_iters: 0
    cac: true

    # Main structure
    rewrite: true
    hybrid: false
    hybrid_old: false

    # Frequency Branch
    freq_emb: 0.2
    emb_scale: 10
    emb_smooth: true

    # Convolutions
    kernel_size: 8
    strides: [4, 4, 2, 2]
    context: 1
    context_enc: 0
    freq_ends: 4
    enc_freq_attn: 0

    # normalization
    norm_starts: 2
    norm_groups: 4

    # DConv residual branch
    dconv_mode: 1
    dconv_depth: 2
    dconv_comp: 4
    dconv_time_attn: 2
    dconv_lstm: 2
    dconv_init: 0.001

    # Weight init
    rescale: 0.1

    lr_sr: 8000
    hr_sr: 16000
    spec_upsample: true
    act_func: snake
    debug: false

  adversarial: true
  features_loss_lambda: 100
  only_features_loss: false
  only_adversarial_loss: false
  discriminator_models: [msd_melgan]
  melgan_discriminator:
    n_layers: 4
    num_D: 3
    downsampling_factor: 4
    ndf: 16
