# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import aero_service_pb2 as aero__service__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in aero_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AeroEnhancementStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnhanceStream = channel.stream_stream(
                '/aero.AeroEnhancement/EnhanceStream',
                request_serializer=aero__service__pb2.AudioChunk.SerializeToString,
                response_deserializer=aero__service__pb2.EnhancedAudioChunk.FromString,
                _registered_method=True)


class AeroEnhancementServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EnhanceStream(self, request_iterator, context):
        """Bi-directional streaming: client sends chunks, server returns enhanced chunks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AeroEnhancementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnhanceStream': grpc.stream_stream_rpc_method_handler(
                    servicer.EnhanceStream,
                    request_deserializer=aero__service__pb2.AudioChunk.FromString,
                    response_serializer=aero__service__pb2.EnhancedAudioChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aero.AeroEnhancement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aero.AeroEnhancement', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AeroEnhancement(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EnhanceStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/aero.AeroEnhancement/EnhanceStream',
            aero__service__pb2.AudioChunk.SerializeToString,
            aero__service__pb2.EnhancedAudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
